---
layout: post
title: Sdu Uitgevers - SaaS product implementation
date: 2010-04-01
author: fcanedo
lang: en
tags:
  - java
  - web-applications
  - saas
  - case-study
---
= Sdu Uitgevers - SaaS product implementation

Lunatech has built and continues to be responsible
for maintaining several of Sdu's web-based law and jurisprudence
document search applications. These applications divide the vast amount
of Dutch law and related information into different areas of law, which
provides added value to lawyers specialised in certain areas, eg.
criminal law or labour law. Customers subscribe on-line to a number of
different applications that give access to these different areas of law
and different subsets of kinds of information (no jurisprudence, for
instance) or access to the complete body of knowledge.

We are responsible for both the front-end software and the back-end
systems that receive, organise and index the large body of text content
that Sdu maintains. This information is organised into different areas
of law, linked, cross-linked and back-linked and ultimately delivered to
the front-end system.
